name: Pack dmg

on:
  workflow_dispatch:
    inputs:
      sumiVersion:
        description: "A valid sumi version, fallback use the value defined in `product.json`"
        required: false
      productVersion:
        description: "product version, fallback use the value defined in `product.json`"
        required: false
      targetArches:
        description: "target arches, use comma to split multi arches"
        required: true
        default: "x64,arm64"
      targetPlatforms:
        description: "target platforms, use comma to split multi arches"
        required: true
        default: "darwin"

jobs:
  next-version:
    name: Pack

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # 判断用户是否有写权限
      - name: "Check if user has write access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Checkout 到
      - uses: actions/checkout@v2
        if: success()

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      # 安装依赖并构建
      - name: Install dependencies & Pack
        run: |
          node ./scripts/apply-product.js
          echo "package.json:" && cat package.json
          echo "./build/package.json" && cat ./build/package.json
          yarn
          yarn download-extension
          yarn run pack
        env:
          SUMI_VERSION: ${{ github.event.inputs.sumiVersion }}
          PRODUCT_VERSION: ${{ github.event.inputs.productVersion }}
          TARGET_ARCHES: ${{ github.event.inputs.targetArches }}

      - uses: actions/upload-artifact@v3
        with:
          name: desktop-artifact arm64
          path: |
            ./out/*-arm64.dmg

      - uses: actions/upload-artifact@v3
        with:
          name: desktop-artifact x64
          path: |
            ./out/*-x64.dmg
