name: RELEASE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node_version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Package Electron
        run: |
          npm i
          npm run rebuild-native
          npm run pack
        env:
          TARGET_PLATFORMS: darwin,win32


      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: true
          files: |
            LICENSE
            out/*.dmg
            out/*.exe

      - name: âœ…
        if: ${{ success() }}
        run: |
          echo æ‰§è¡ŒæˆåŠŸ

      - name: ğŸš¨
        if: ${{ failure() }}
        run: |
          echo æ‰§è¡Œå¤±è´¥
